#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sumOfEvenFibonacci(numRange):
	prevFib=1 #Starting with zeroth term of Fibonacci: 1
	current = 1 #First term of Fibonacci:1
	sumOfEvenNums = 0 #The result.
	while 1:
		fibNext = current + prevFib #Calculate the next Fibonacci number
		if fibNext > numRange:		#Range control
			break
		else:
			if fibNext%2 == 0:		#Add the even ones
				sumOfEvenNums += fibNext
			prevFib = current		#Update the previous terms to get ready to calculate the next Fibonacci number
			current = fibNext
	print (sumOfEvenNums)

sumOfEvenFibonacci(4000000)
